### ISSUE TITLE
acmart dependency out of date

### ISSUE THREAD

**Issue by henrixapp** [AlgoEngHeidelberg/AEseminars#1]
This project ships with v1.73 of acmart, the newest version is v1.81 (https://ctan.org/pkg/acmart?lang=en).

When compiling a simple test document with mactex distribution (2021), an error occurs, that has been fixed in acmart (https://github.com/borisveytsman/acmart/issues/421). 

This error only occurs, when using a newer typesetter, older distribution of mactex(~2018) works fine.

**Comment by schulzchristian** [comment]
Feel free to issue a pull request, will be happy to merge it.

Thank you
Christian
